import type { ConsumptionLog, FilamentRoll } from "@/lib/types";

export const demoRolls: FilamentRoll[] = [
  {
    id: "demo-bambu-jade-white",
    brand: "Bambu Lab",
    product_line: "PLA Basic",
    material: "PLA",
    color_name: "Jade White",
    color_hex: "#f7f4e8",
    initial_weight_g: 1000,
    available_weight_g: 820,
    low_threshold_g: 200,
    status: "open",
    location: "AMS Slot 1",
    purchase_date: "2026-08-20",
    price_amount: 19.99,
    currency: "USD",
    supplier_id: null,
    supplier_name: "Bambu Lab",
    package_type: "spooled",
    spool_id: null,
    spool_cost_amount: 0,
    filament_cost_amount: 19.99,
    drying_notes: "Secado 4 h a 50 C antes de guardar.",
    photo_url: null,
    purchase_url: "https://us.store.bambulab.com/",
    nfc_tag_id: null,
    qr_payload: "filament-roll:demo-bambu-jade-white"
  },
  {
    id: "demo-bambu-matte-charcoal",
    brand: "Bambu Lab",
    product_line: "PLA Matte",
    material: "PLA",
    color_name: "Charcoal",
    color_hex: "#2f3437",
    initial_weight_g: 1000,
    available_weight_g: 145,
    low_threshold_g: 200,
    status: "low",
    location: "Gaveta seca",
    purchase_date: "2026-07-12",
    price_amount: 22.99,
    currency: "USD",
    supplier_id: null,
    supplier_name: "Bambu Lab",
    package_type: "spooled",
    spool_id: null,
    spool_cost_amount: 0,
    filament_cost_amount: 22.99,
    drying_notes: "Excelente para figuras; revisar stock pronto.",
    photo_url: null,
    purchase_url: "https://us.store.bambulab.com/",
    nfc_tag_id: null,
    qr_payload: "filament-roll:demo-bambu-matte-charcoal"
  },
  {
    id: "demo-pritonic-blue",
    brand: "Pritonic",
    product_line: "Genérico",
    material: "PLA",
    color_name: "Azul",
    color_hex: "#2563eb",
    initial_weight_g: 1000,
    available_weight_g: 510,
    low_threshold_g: 200,
    status: "open",
    location: "SUNLU",
    purchase_date: null,
    price_amount: null,
    currency: "USD",
    supplier_id: null,
    supplier_name: null,
    package_type: "spooled",
    spool_id: null,
    spool_cost_amount: 0,
    filament_cost_amount: null,
    drying_notes: "Marca genérica; perfilar temperatura si da stringing.",
    photo_url: null,
    purchase_url: null,
    nfc_tag_id: null,
    qr_payload: "filament-roll:demo-pritonic-blue"
  }
];

export const demoLogs: ConsumptionLog[] = [
  {
    id: "demo-log-1",
    roll_id: "demo-bambu-jade-white",
    project_name: "Soporte para herramientas",
    grams_used: 180,
    consumed_at: "2026-08-24",
    notes: "Impreso en Bambu P1S.",
    cost_amount: null,
    currency: null
  },
  {
    id: "demo-log-2",
    roll_id: "demo-bambu-matte-charcoal",
    project_name: "Base para miniatura",
    grams_used: 92,
    consumed_at: "2026-08-23",
    notes: null,
    cost_amount: null,
    currency: null
  }
];
